namespace: servicenow
name: itsm
version: 2.16.0
readme: README.md
authors:
  - Ansible Eco Content Team (github.com/eco-ansible-content)
description: Ansible Collection for interacting with ServiceNow ITSM
license_file: LICENSE
tags:
  - servicenow
  - application
  - infrastructure
repository: https://github.com/ansible-collections/servicenow.itsm
homepage: https://github.com/ansible-collections/servicenow.itsm
issues: https://github.com/ansible-collections/servicenow.itsm/issues
build_ignore:
  # general
  - changelogs/.plugin-cache.yaml
  - .pytest_cache
  - .gitignore
  - .vscode
  - sonar-project.properties
  - .ansible
  - .github
  - CODEOWNERS
  - CONTRIBUTING.md

  # AI
  - .claude
  - .cursor
  - .lola
  - .lola-req
  - AGENTS.md
  - coderabbit.yml
  - .agents

  # project specific
  - scripts
  - tests/integration/targets/*/test_session
  - tests/integration/targets/*/roles
  - tests/integration/integration_config.yml
